import turtle
ablak=turtle.Screen()
ablak.bgcolor("lightgreen")
Teknőske=turtle.Turtle()
Teknőske.shape("turtle")
Teknőske.color("brown")
Teknőske.speed(1)

Teknőske.forward(50)
Teknőske.right(144)
Teknőske.forward(100)
Teknőske.right(144)
Teknőske.forward(100)
Teknőske.right(144)
Teknőske.forward(100)
Teknőske.right(144)
Teknőske.forward(100)
Teknőske.right(144)
Teknőske.forward(50)
ablak.mainloop()