import turtle
ablak=turtle.Screen()
ablak.bgcolor("lightgreen")
Gazsi=turtle.Turtle()
Gazsi.shape("turtle")
Gazsi.color("brown")
Robika=turtle.Turtle()
Robika.shape("turtle")
Robika.color("black")
Dzsúlió=turtle.Turtle()
Dzsúlió.shape("turtle")
Dzsúlió.color("blue")
Szebásztiján=turtle.Turtle()
Szebásztiján.shape("turtle")
Szebásztiján.color("yellow")



Gazsi.forward(100)
Gazsi.left(120)
Gazsi.forward(100)
Gazsi.left(120)
Gazsi.forward(100)
Gazsi.left(120)

Robika.forward(100)
Robika.left(90)
Robika.forward(100)
Robika.left(90)
Robika.forward(100)
Robika.left(90)
Robika.forward(100)

Dzsúlió.forward(100)
Dzsúlió.left(60)
Dzsúlió.forward(100)
Dzsúlió.left(60)
Dzsúlió.forward(100)
Dzsúlió.left(60)
Dzsúlió.forward(100)
Dzsúlió.left(60)
Dzsúlió.forward(100)
Dzsúlió.left(60)
Dzsúlió.forward(100)

Szebásztiján.forward(100)
Szebásztiján.left(45)
Szebásztiján.forward(100)
Szebásztiján.left(45)
Szebásztiján.forward(100)
Szebásztiján.left(45)
Szebásztiján.forward(100)
Szebásztiján.left(45)
Szebásztiján.forward(100)
Szebásztiján.left(45)
Szebásztiján.forward(100)
Szebásztiján.left(45)
Szebásztiján.forward(100)
Szebásztiján.left(45)
Szebásztiján.forward(100)

Szebásztiján.left(1000)
