import turtle
ablak=turtle.Screen()
ablak.bgcolor("lightgreen")
Teknőske=turtle.Turtle()
Teknőske.shape("turtle")
Teknőske.color("brown")
Teknőske.speed(10)


Teknőske.forward(80)
Teknőske.left(20)
Teknőske.forward(80)
Teknőske.left(20)
Teknőske.forward(80)
Teknőske.left(20)
Teknőske.forward(80)
Teknőske.left(20)
Teknőske.forward(80)
Teknőske.left(20)
Teknőske.forward(80)
Teknőske.left(20)
Teknőske.forward(80)
Teknőske.left(20)
Teknőske.forward(80)
Teknőske.left(20)
Teknőske.forward(80)
Teknőske.left(20)
Teknőske.forward(80)
Teknőske.left(20)
Teknőske.forward(80)
Teknőske.left(20)
Teknőske.forward(80)
Teknőske.left(20)
Teknőske.forward(80)
Teknőske.left(20)
Teknőske.forward(80)
Teknőske.left(20)
Teknőske.forward(80)
Teknőske.left(20)
Teknőske.forward(80)
Teknőske.left(20)
Teknőske.forward(80)
Teknőske.left(20)
Teknőske.forward(80)
print("20 fokkal kell elfordulnia minden alkalommal a teknősnek.")
ablak.mainloop()